### ISSUE TITLE
Cleanup unused code, comments, etc.

### ISSUE THREAD

**Issue by dblock** [AmiStrn/opensearch-plugin-template#6]
There's a lot going on in things like Gradle scripts that I am not sure is actually used. For example https://github.com/AmiStrn/opensearch-plugin-template/blob/main/build.gradle#L24 - since this is a template repo for plugins, strip out anything that's not absolutely necessary. Otherwise explain and document.

**Comment by AmiStrn** [comment]
This is a good point. This gradle script is from the anomaly-detection plugin, and the comments are from there as well. I agree this should be better documented.

**Comment by dblock** [comment]
Consider naming things with `renameme` instead of `plugin` or `path.to.plugin`. This way the README can be simplified to just say `rename all "renameme" to "plugin-name"`.

**Comment by AmiStrn** [comment]
solved by #7 closing this issue:)
